# Generated by Django 6.1.1 on 2026-09-28 16:45

import catalog.image_processing
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('barcode', models.CharField(blank=True, max_length=64, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('brand', models.CharField(blank=True, default='', max_length=120)),
                ('unit_of_measure', models.CharField(choices=[('UNIDAD', 'Unidad'), ('PAQUETE', 'Paquete'), ('BULTO', 'Bulto'), ('CAJA', 'Caja'), ('LIBRA', 'Libra'), ('KILO', 'Kilogramo'), ('LITRO', 'Litro'), ('UNIDAD_FISICA', 'Unidad física')], default='UNIDAD', max_length=20)),
                ('units_per_package', models.PositiveIntegerField(default=1, help_text='Unidades internas contenidas en un paquete/bulto para el ingreso de mercancía.', validators=[django.core.validators.MinValueValidator(1)])),
                ('cost_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Costo de compra (USD)')),
                ('price_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))], verbose_name='Precio de venta (USD)')),
                ('stock', models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))])),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_pro_name_f603c0_idx'), models.Index(fields=['is_active'], name='catalog_pro_is_acti_14fc6b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('units_per_package__gte', 1)), name='product_units_per_package_gte_1'), models.CheckConstraint(condition=models.Q(('stock__gte', 0)), name='product_stock_gte_0'), models.CheckConstraint(condition=models.Q(('cost_usd__gte', 0), ('price_usd__gte', 0)), name='product_amounts_gte_0')],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(max_length=255, upload_to=catalog.image_processing.build_upload_path)),
                ('thumbnail', models.ImageField(blank=True, max_length=255, upload_to=catalog.image_processing.build_upload_path)),
                ('original_filename', models.CharField(blank=True, default='', max_length=255)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('size_bytes', models.PositiveIntegerField(default=0)),
                ('is_primary', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.product')),
            ],
            options={
                'ordering': ['-is_primary', 'sort_order', 'id'],
                'indexes': [models.Index(fields=['product', 'sort_order'], name='catalog_pro_product_4ee3b8_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_primary', True)), fields=('product',), name='one_primary_image_per_product')],
            },
        ),
    ]
