# Generated by Django 6.1.1 on 2026-09-28 18:00

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pending_units',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Unidades vendidas sin existencia disponible cuando la tienda permite vender con stock cero. Las entradas futuras las cancelan primero.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), editable=False, help_text='Unidades físicamente disponibles (nunca negativo).', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.000'))]),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('pending_units__gte', 0)), name='product_pending_units_gte_0'),
        ),
    ]
