# Generated by Django 6.1.1 on 2026-09-29 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_pending_units_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='source',
            field=models.CharField(blank=True, default='', help_text='Origen del alta, por ejemplo "costazul". Vacio cuando es manual.', max_length=40),
        ),
        migrations.AddField(
            model_name='product',
            name='source_ref',
            field=models.CharField(blank=True, default='', help_text='Identificador estable en el origen, para reimportar sin duplicar.', max_length=64),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['source', 'source_ref'], name='catalog_pro_source_9198d0_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(condition=models.Q(('source', ''), _negated=True), fields=('source', 'source_ref'), name='one_product_per_source_ref'),
        ),
    ]
