# Generated by Django 6.1.1 on 2026-09-30 01:11

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_product_source_product_source_ref_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='surcharge_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Recargo propio del artículo. Vacío = hereda el de su categoría, o el de la tienda si tampoco tiene categoría.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Recargo del artículo (%)'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=16, unique=True)),
                ('name', models.CharField(help_text='Nombre de la categoría, por ejemplo "Abarrotes" o "Lácteos".', max_length=120, unique=True)),
                ('surcharge_percentage', models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Se aplica a los artículos de la categoría que no tengan recargo propio. Vacío = hereda el recargo de la tienda.', max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))], verbose_name='Recargo de la categoría (%)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Categoría',
                'verbose_name_plural': 'Categorías',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='catalog_cat_name_39f70b_idx'), models.Index(fields=['is_active'], name='catalog_cat_is_acti_7db955_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('surcharge_percentage__isnull', True), models.Q(('surcharge_percentage__gte', Decimal('0.00')), ('surcharge_percentage__lte', Decimal('100.00'))), _connector='OR'), name='category_surcharge_between_0_and_100')],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='products', to='catalog.category', verbose_name='Categoría'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_percentage__isnull', True), models.Q(('surcharge_percentage__gte', Decimal('0.00')), ('surcharge_percentage__lte', Decimal('100.00'))), _connector='OR'), name='product_surcharge_between_0_and_100'),
        ),
    ]
