# Generated by Django 6.1.1 on 2026-09-28 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExitNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('reason', models.CharField(choices=[('MERMA', 'Merma'), ('CONSUMO_INTERNO', 'Consumo interno'), ('PERDIDA', 'Pérdida'), ('DEVOLUCION', 'Devolución de mercancía'), ('DANO', 'Producto dañado'), ('VENCIMIENTO', 'Vencimiento'), ('OTRO', 'Otro')], max_length=20)),
                ('description', models.TextField()),
                ('exit_date', models.DateField()),
                ('total_units', models.DecimalField(decimal_places=3, default=Decimal('0.000'), max_digits=14)),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_notes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nota de salida',
                'verbose_name_plural': 'Notas de salida',
                'ordering': ['-exit_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ExitNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.exitnote')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exit_note_items', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('supplier_name', models.CharField(blank=True, default='', max_length=150)),
                ('entry_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (VES)')], default='USD', max_length=3)),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=4, help_text='Tasa VES/USD aplicada cuando el costo se registró en bolívares.', max_digits=14, null=True)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_cancelled', models.BooleanField(default=False)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='goods_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de mercancía',
                'verbose_name_plural': 'Entradas de mercancía',
                'ordering': ['-entry_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='GoodsEntryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (VES)')], default='USD', max_length=3)),
                ('rate_applied', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inventory.goodsentry')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entry_items', to='catalog.product')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('origin', models.CharField(choices=[('ENTRADA', 'Entrada de mercancía'), ('VENTA', 'Venta'), ('NOTA_SALIDA', 'Nota de salida'), ('ANULACION', 'Anulación')], max_length=20)),
                ('origin_id', models.IntegerField(blank=True, help_text='PK del documento origen.', null=True)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('balance_after', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_price_usd', models.DecimalField(blank=True, decimal_places=2, help_text='Precio de venta unitario en el momento del movimiento (sólo ventas).', max_digits=12, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.product')),
                ('reversal_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reversals', to='inventory.stockmovement')),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='exitnote',
            index=models.Index(fields=['-exit_date'], name='inventory_e_exit_da_596b73_idx'),
        ),
        migrations.AddConstraint(
            model_name='exitnoteitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='exit_item_quantity_gt_0'),
        ),
        migrations.AddIndex(
            model_name='goodsentry',
            index=models.Index(fields=['-entry_date'], name='inventory_g_entry_d_f71dea_idx'),
        ),
        migrations.AddConstraint(
            model_name='goodsentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='entry_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='goodsentryitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_cost__gt', 0)), name='entry_item_unit_cost_gt_0'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['product', '-occurred_at'], name='inventory_s_product_5ccbf2_idx'),
        ),
        migrations.AddIndex(
            model_name='stockmovement',
            index=models.Index(fields=['origin', 'origin_id'], name='inventory_s_origin_67be91_idx'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stock_movement_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('balance_after__gte', 0)), name='stock_movement_balance_gte_0'),
        ),
    ]
