# Generated by Django 6.1.1 on 2026-09-28 18:00

from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_product_pending_units_alter_product_stock_and_more'),
        ('inventory', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockmovement',
            name='pending_after',
            field=models.DecimalField(decimal_places=3, default=Decimal('0.000'), help_text='Unidades pendientes de reposición tras este movimiento.', max_digits=12),
        ),
        migrations.AddConstraint(
            model_name='stockmovement',
            constraint=models.CheckConstraint(condition=models.Q(('pending_after__gte', 0)), name='stock_movement_pending_gte_0'),
        ),
    ]
