# Generated by Django 6.1.1 on 2026-09-28 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('customers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(editable=False, max_length=32, unique=True)),
                ('sale_type', models.CharField(choices=[('PAID', 'Venta pagada'), ('CREDIT', 'Venta fiada (crédito)')], default='PAID', max_length=10)),
                ('sale_date', models.DateField()),
                ('currency', models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (VES)')], default='USD', help_text='Moneda en la que el cliente pagó o se fia.', max_length=3)),
                ('exchange_rate_applied', models.DecimalField(decimal_places=4, help_text='Tasa VES/USD vigente en el momento de la venta (inmutable).', max_digits=14)),
                ('surcharge_percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo aplicado (%), copiado de la configuración en el momento de la venta.', max_digits=6)),
                ('subtotal_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('surcharge_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('total_ves', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=16)),
                ('payment_method', models.CharField(choices=[('CASH_USD', 'Efectivo USD'), ('CASH_VES', 'Efectivo VES'), ('TRANSFER_USD', 'Transferencia USD'), ('TRANSFER_VES', 'Transferencia VES'), ('MIXED', 'Mixto'), ('CARD', 'Punto de venta')], default='CASH_USD', max_length=16)),
                ('amount_due_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completada'), ('ANULLED', 'Anulada')], default='COMPLETED', max_length=12)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='customers.customer')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['-sale_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='CustomerDebt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('paid_amount_usd', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=14)),
                ('balance_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('status', models.CharField(choices=[('OPEN', 'Pendiente'), ('PAID', 'Pagada'), ('ANULLED', 'Anulada')], default='OPEN', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debts', to='customers.customer')),
                ('sale', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='debt', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Deuda de cliente',
                'verbose_name_plural': 'Deudas de clientes',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.001'))])),
                ('unit_price_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('line_total_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('unit_cost_usd', models.DecimalField(decimal_places=2, help_text='Costo congelado al momento de la venta.', max_digits=12)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_items', to='catalog.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='sales.sale')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('USD', 'Dólares (USD)'), ('VES', 'Bolívares (VES)')], max_length=3)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('exchange_rate_applied', models.DecimalField(decimal_places=4, help_text='Tasa vigente en la fecha del abono. Un abono en VES usa la tasa de ese día.', max_digits=14)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=14)),
                ('method', models.CharField(choices=[('CASH_USD', 'Efectivo USD'), ('CASH_VES', 'Efectivo VES'), ('TRANSFER_USD', 'Transferencia USD'), ('TRANSFER_VES', 'Transferencia VES'), ('MIXED', 'Mixto'), ('CARD', 'Punto de venta')], max_length=16)),
                ('paid_at', models.DateTimeField()),
                ('is_voided', models.BooleanField(default=False)),
                ('voided_at', models.DateTimeField(blank=True, null=True)),
                ('void_reason', models.CharField(blank=True, default='', max_length=255)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to='sales.customerdebt')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='debt_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Abono de deuda',
                'verbose_name_plural': 'Abonos de deudas',
                'ordering': ['-paid_at', '-id'],
                'indexes': [models.Index(fields=['debt', '-paid_at'], name='sales_debtp_debt_id_715e43_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='debt_payment_amount_gt_0'), models.CheckConstraint(condition=models.Q(('amount_usd__gt', 0)), name='debt_payment_amount_usd_gt_0')],
            },
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-sale_date'], name='sales_sale_sale_da_22fba2_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['sale_type', '-sale_date'], name='sales_sale_sale_ty_61b241_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['customer', '-sale_date'], name='sales_sale_custome_4a0f8d_idx'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('total_usd__gte', 0)), name='sale_total_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('amount_due_usd__gte', 0)), name='sale_amount_due_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='sale',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_percentage__gte', 0)), name='sale_surcharge_gte_0'),
        ),
        migrations.AddIndex(
            model_name='customerdebt',
            index=models.Index(fields=['customer', 'status'], name='sales_custo_custome_45a305_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerdebt',
            constraint=models.CheckConstraint(condition=models.Q(('balance_usd__gte', 0)), name='debt_balance_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='customerdebt',
            constraint=models.CheckConstraint(condition=models.Q(('paid_amount_usd__gte', 0)), name='debt_paid_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='sale_item_quantity_gt_0'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price_usd__gte', 0)), name='sale_item_unit_price_gte_0'),
        ),
    ]
