# Generated by Django 6.1.1 on 2026-09-30 01:11

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_product_surcharge_percentage_category_and_more'),
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='surcharge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo congelado en esta línea, ya sea del artículo, de su categoría, de la tienda o elegido en el carrito.', max_digits=6),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='surcharge_source',
            field=models.CharField(choices=[('MANUAL', 'Elegido en el carrito'), ('PRODUCT', 'Artículo'), ('CATEGORY', 'Categoría'), ('STORE', 'Tienda')], default='STORE', help_text='Nivel del que salió el recargo aplicado en esta línea.', max_length=10),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='surcharge_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Importe del recargo de la línea, calculado sobre line_total_usd.', max_digits=14),
        ),
        migrations.AlterField(
            model_name='sale',
            name='surcharge_percentage',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Recargo efectivo de la venta, como porcentaje ponderado por el importe de cada línea (surge_usd / subtotal_usd * 100). Las ventas anteriores al recargo por línea guardaban aquí un único porcentaje global; el valor sigue siendo válido.', max_digits=6),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_usd__gte', 0)), name='sale_item_surcharge_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='saleitem',
            constraint=models.CheckConstraint(condition=models.Q(('surcharge_percentage__gte', 0), ('surcharge_percentage__lte', Decimal('100.00'))), name='sale_item_surcharge_between_0_and_100'),
        ),
    ]
