# Generated by Django 6.1.1 on 2026-09-28 16:45

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=4, help_text='Bolívares por 1 USD (VES por USD).', max_digits=14, validators=[django.core.validators.MinValueValidator(Decimal('0.0001'))])),
                ('effective_date', models.DateField(help_text='Fecha de vigencia publicada por el BCV.')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, help_text='Fecha y hora real de consulta al BCV.')),
                ('source', models.CharField(choices=[('BCV', 'BCV (oficial)'), ('MANUAL', 'Manual (fallback)')], default='BCV', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.CharField(blank=True, default='', max_length=255)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_exchange_rates', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tasa de cambio',
                'verbose_name_plural': 'Tasas de cambio',
                'ordering': ['-effective_date', '-id'],
                'indexes': [models.Index(fields=['-effective_date'], name='rates_excha_effecti_ce54fc_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('rate__gt', 0)), name='exchange_rate_gt_0'), models.UniqueConstraint(fields=('source', 'effective_date'), name='unique_rate_per_source_and_date')],
            },
        ),
    ]
